class Form{
    constructor(){
        this.back=createButton('BACK')
        this.back.hide()
        
        this.title=createElement('h2',"BORED OF BEING BORED???")
        this.title.style('font-family:Agency FB')
        this.button1 = createButton("movies&series")
        this.button1.style('border-radius:12px')
        this.button1.style('background-color:pink')
        this.button1.style('font-size:20px')

        this.button2 = createButton("songs")
        this.button2.style('border-radius:12px')
        this.button2.style('background-color:pink')
        this.button2.style('font-size:20px')

        this.button3 = createButton("games")
        this.button3.style('border-radius:12px')
        this.button3.style('background-color:pink')
        this.button3.style('font-size:20px')
        
        this.button4 = createButton("art&craft")
        this.button4.style('border-radius:12px')
        this.button4.style('background-color:pink')
        this.button4.style('font-size:20px')

        this.m1=createA("https://www.netflix.com/browse","NETFLIX","_blank")
        this.m1.style('color:white')
        this.m1.style('font-size:22px')
        this.m2=createA("https://www.primevideo.com/?ref_=dvm_pds_amz_in_as_s_g_brand12&ext_vrnc=hi%7Cm_JbhoVIy5c_c386559716616_s","PRIME VIDEO","_blank")
        this.m2.style('color:white')
        this.m2.style('font-size:22px')
        this.m3=createA("https://www.hotstar.com/in","HOTSTAR","_blank")
        this.m3.style('color:white')
        this.m3.style('font-size:22px')
        this.m4=createA("https://fmovies.co/","FMOVIES","_blank")
        this.m4.style('color:white')
        this.m4.style('font-size:22px')
        this.m5=createA("https://www.popcornflix.com/pages/discover/d/movies","POPCORNFLIX","_blank")
        this.m5.style('color:white')
        this.m5.style('font-size:22px')

        this.s1=createA("https://www.spotify.com/in/free/?utm_source=in-en_brand_contextual_text&utm_medium=paidsearch&utm_campaign=alwayson_asia_in_premiumbusiness_core_brand+contextual-desktop+text+exact+in-en+google&ds_rl=1270915&gclid=CjwKCAjw8pH3BRAXEiwA1pvMsWwZfbI_yM7JGrVxT1Qb91y0VFtqXfwTKbDkkCnBvJhGdkrtNpXDQxoCwu8QAvD_BwE&gclsrc=aw.ds","SPOTIFY","_blank")
        this.s1.style('color:white')
        this.s1.style('font-size:28px')
        this.s2=createA("https://www.youtube.com/musicpremium","YOUTUBE MUSIC","_blank")
        this.s2.style('color:white')
        this.s2.style('font-size:28px')
        this.s3=createA("https://wynk.in/music","WYNK MUSIC","_blank")
        this.s3.style('color:white')
        this.s3.style('font-size:28px')
        this.s4=createA("https://gaana.com/","GAANA","_blank")
        this.s4.style('color:white')
        this.s4.style('font-size:28px')
        this.s5=createA("https://www.jiosaavn.com/","SAAVN","_blank")
        this.s5.style('color:white')
        this.s5.style('font-size:28px')

        this.g1=createA("https://play.google.com/store/apps/details?id=com.ludo.king&hl=en_IN","LUDO KING","_blank")
        this.g1.style('color:black')
        this.g1.style('font-size:28px')
        this.g2=createA("https://play.google.com/store/apps/details?id=com.matteljv.uno&hl=en_IN","UNO","_blank")
        this.g2.style('color:black')
        this.g2.style('font-size:28px')
        this.g3=createA("https://play.google.com/store/apps/details?id=com.prettysimple.criminalcaseandroid&hl=en_IN","CRIMINAL CASE","_blank")
        this.g3.style('color:black')
        this.g3.style('font-size:28px')
        this.g4=createA("https://www.arkadium.com/free-online-games/puzzles/","PUZZLES","_blank")
        this.g4.style('color:black')
        this.g4.style('font-size:28px')
        this.g5=createA("https://www.retrogames.cz/play_085-NES.php?language=EN","BOMBERMAN","_blank")
        this.g5.style('color:black')
        this.g5.style('font-size:28px')

        this.a1=createA("https://in.pinterest.com/search/pins/?q=sketching&rs=typed&term_meta[]=sketching%7Ctyped","SKETCHING","_blank")
        this.a1.style('color:white')
        this.a1.style('font-size:22px')
        this.a2=createA("https://in.pinterest.com/search/pins/?q=painting&rs=typed&term_meta[]=painting%7Ctyped","PAINTING","_blank")
        this.a2.style('color:white')
        this.a2.style('font-size:22px')
        this.a3=createA("","DOODLING","_blank")
        this.a3.style('color:white')
        this.a3.style('font-size:22px')
        this.a4=createA("https://www.youtube.com/channel/UC295-Dw_tDNtZXFeAPAW6Aw","5MINUTECRAFTS","_blank")
        this.a4.style('color:white')
        this.a4.style('font-size:22px')
        this.a5=createA("https://in.pinterest.com/topics/diy-crafts/","DIYs","_blank")
        this.a5.style('color:white')
        this.a5.style('font-size:22px')

    }
    hide(){
        this.m1.hide()
        this.m2.hide()
        this.m3.hide()
        this.m4.hide()
        this.m5.hide()
        this.s1.hide()
        this.s2.hide()
        this.s3.hide()
        this.s4.hide()
        this.s5.hide()
        this.g1.hide()
        this.g2.hide()
        this.g3.hide()
        this.g4.hide()
        this.g5.hide()
        this.a1.hide()
        this.a2.hide()
        this.a3.hide()
        this.a4.hide()
        this.a5.hide()
    }
    display(){
        this.title.position(displayWidth/2-125,100)
        this.button1.position(displayWidth/2-300,250)
        this.button2.position(displayWidth/2-100,250)
        this.button3.position(displayWidth/2+50,250)
        this.button4.position(displayWidth/2+200,250)

            this.button1.mousePressed(()=>{
            c=1
            this.back.show()
            this.back.position(displayWidth-100,20)
            this.title.hide()
            this.button1.hide()
            this.button2.hide()
            this.button3.hide()
            this.button4.hide()
            this.m1.position(displayWidth/2-50,100)
            this.m2.position(displayWidth/2-50,200)
            this.m3.position(displayWidth/2-50,300)
            this.m4.position(displayWidth/2-50,400)
            this.m5.position(displayWidth/2-50,500)
            this.m1.show()
            this.m2.show()
            this.m3.show()
            this.m4.show()
            this.m5.show()
            })

            this.button2.mousePressed(()=>{
            c=2
            this.back.show()
            this.back.position(displayWidth-100,20)
            this.title.hide()
            this.button1.hide()
            this.button2.hide()
            this.button3.hide()
            this.button4.hide()
            this.s1.position(displayWidth/2-50,100)
            this.s2.position(displayWidth/2-50,200)
            this.s3.position(displayWidth/2-50,300)
            this.s4.position(displayWidth/2-50,400)
            this.s5.position(displayWidth/2-50,500)
            this.s1.show()
            this.s2.show()
            this.s3.show()
            this.s4.show()
            this.s5.show()
            })

            this.button3.mousePressed(()=>{
            c=3
            this.back.show()
            this.back.position(displayWidth-100,20)
            this.title.hide()
            this.button1.hide()
            this.button2.hide()
            this.button3.hide()
            this.button4.hide()
            this.g1.position(displayWidth/2-50,100)
            this.g2.position(displayWidth/2-50,200)
            this.g3.position(displayWidth/2-50,300)
            this.g4.position(displayWidth/2-50,400)
            this.g5.position(displayWidth/2-50,500)
            this.g1.show()
            this.g2.show()
            this.g3.show()
            this.g4.show()
            this.g5.show()
            })

            this.button4.mousePressed(()=>{
            c=4
            this.back.show()
            this.back.position(displayWidth-100,20)
            this.title.hide()
            this.button1.hide()
            this.button2.hide()
            this.button3.hide()
            this.button4.hide()
            this.a1.position(displayWidth/2-50,200)
            this.a2.position(displayWidth/2-50,300)
            this.a3.position(displayWidth/2-50,400)
            this.a4.position(displayWidth/2-50,500)
            this.a5.position(displayWidth/2-50,600)
            this.a1.show()
            this.a2.show()
            this.a3.show()
            this.a4.show()
            this.a5.show()
            })
            this.back.mousePressed(()=>{
                c=0
                this.button1.show()
                this.button2.show()
                this.button3.show()
                this.button4.show()
                this.hide()
                this.back.hide()
                this.title.show()
            })
    }
}